### ISSUE TITLE
Dependency of gnome-tweak-tools

### ISSUE THREAD

**Issue by grosbedos** [NuTyX/gnome#11]
Hi,

When i launch gnome tweak tools, it fails to launch.
`ImportError: No module named gi`

I think you should add depency python-gobject for package gnome-tweak-tools

Best regards

**Comment by tnut** [comment]
Hmm I was shure I did that. will check again

**Comment by jaycenet** [comment]
Problème résolu avec la recette => gnome-tweak-tool 3.24.1-2

**Comment by tnut** [comment]
Merci pour ton taffe jaycenet

**Comment by grosbedos** [comment]
Thanks a lot
