### ISSUE TITLE
Mise à jour vers 3.26

### ISSUE THREAD

**Issue by jaycenet** [NuTyX/gnome#12]
Mettre à jour gnome vers la version 3.26

**Comment by tnut** [comment]
Merci de te l'avoir assigné. J'espère aussi qu'il fonctionnera à nouveau. Aujourd'hui il ne fonctionne plus sur la branche "development"

**Comment by tnut** [comment]
Nous sommes en discussion sur la salon discords. La question est de savoir si l'on souhaite maintenir cette interface graphique ou non et si non on déplace les applications gnome bien utiles dans core et extra. ?

**Comment by jaycenet** [comment]
C'est vrai que c'est assez complexe de maintenir cette interface, surtout qu'elle se base beaucoup sur systemd et wayland.

**Comment by tnut** [comment]
J'ai ouvert un nouveau post sur le Forum, n'hésites pas à réagir et faire part de ton opignion

**Comment by tnut** [comment]
Fait
