### ISSUE TITLE
blocked at step 10

### ISSUE THREAD

**Issue by bertux** [NuTyX/gnome#2]
When tried on a formated partition it goes well until the step 10 where the command "cards level" replies :
WARNING openssh from /houaphan/gnome/gnome-keyring NOT FOUND ...
WARNING telepathy-mission-control from /houaphan/gnome/gnome-shell NOT FOUND ...
WARNING vte3 from /houaphan/gnome/gnome-color-manager NOT FOUND ...

When I comment /houaphan/gnome in /etc/cards.conf the same command works without problem and finishes by :
17: /houaphan/gui/gcr
17: /houaphan/gui/colord-gtk
17: /houaphan/gui/xorg-xclock
17: /houaphan/gui/libdbusmenu-qt
18: /houaphan/gui/xorg
18: /houaphan/gui/xine-lib
18: /houaphan/gui/libcanberra
18: /houaphan/gui/virtuoso
18: /houaphan/gui/geoclue
18: /houaphan/gui/python-gtksourceview2
18: /houaphan/gui/python-rsvg
18: /houaphan/gui/keybinder2
18: /houaphan/gui/python-notify
18: /houaphan/gui/zenity
19: /houaphan/gui/webkitgtk2
19: /houaphan/gui/openbox
19: /houaphan/gui/notification-daemon
19: /houaphan/gui/webkit2gtk3
19: /houaphan/gui/webkitgtk3
19: /houaphan/gui/qt5
20: /houaphan/gui/poppler-qt5
20: /houaphan/gui/yelp

So I suppose it's a bug in this gnome repository and I wait for the fix.

**Comment by tnut** [comment]
You right vte3 and  telepathy-mission-control should be in the gui collection

For openssh, sync base-extra (from extra)

**Comment by bertux** [comment]
Now it works for me after syncing base-extra as explained in the README.md of its github repository so I  will add this step in the README.md of gnome.

**Comment by bertux** [comment]
j'ai corrigé cli-extra par base-extra avec le commit https://github.com/NuTyX/gnome/commit/e01b13a0f2e5690366a2e7fb3a3973f562c27ffe car openssh n'est pas dans cli-extra mais dans base-extra
